#!/usr/bin/env python
import roslib; roslib.load_manifest('teleop_twist_keyboard')
import rospy
import math

from geometry_msgs.msg import Twist
from std_msgs.msg import String

import sys, select, termios, tty
msg = """
Reading from the keyboard  and Publishing to Twist!
"""
	
def listener1():
    global twist
    rospy.Subscriber('/cmd_vel_sim', Twist, talker1)
    # Initial movement.
    twist = Twist()
    twist.linear.x = 0; twist.linear.y = 0; twist.linear.z = 0;
    twist.angular.x = 0; twist.angular.y = 0; twist.angular.z = 0;
    #pub.publish(twist)
    rospy.spin()
	
def talker1(data):
    cmdvelsim.lin.x=data.linear.x
    cmdvelsim.ang.z=data.angular.z
    return cmdvelsim.lin.x, cmdvelsim.ang.z
	
def listener2():
    global twist
    rospy.Subscriber('/dm_init', Twist, talker2)
    # Initial movement.
    twist = Twist()
    twist.linear.x = 0; twist.linear.y = 0; twist.linear.z = 0;
    twist.angular.x = 0; twist.angular.y = 0; twist.angular.z = 0;
    #pub.publish(twist)
    rospy.spin()
	
def talker2(data):
    dm.lin.x=data.linear.x
    dm.ang.z=data.angular.z
    return dm.lin.x, dm.ang.z
	
def talker():
    global twist
    twist = Twist()
    #twist.linear.x = 0; twist.linear.y = 0; twist.linear.z = 0;
    #twist.angular.x = 0; twist.angular.y = 0; twist.angular.z = 0;
    twist.linear.x = cmdvelsim.lin.x * dm.lin.x 
    twist.angular.z = cmdvelsim.ang.z * dm.ang.z
    pub.publish(twist)


if __name__ == '__main__':
    	settings = termios.tcgetattr(sys.stdin)
	pub = rospy.Publisher('cmd_vel', Twist, queue_size = 1)
	rospy.init_node('deadman', anonymous=True)
	try:
		print msg
        	listener()
		
   	except rospy.ROSInterruptException:
        	pass
